"""
Global constants for Swachh-Seva.
All statuses, roles, categories and enums live here — no magic strings in code.
"""

# ================= ROLES =================
ROLE_CITIZEN = 'CITIZEN'
ROLE_WORKER = 'WORKER'
ROLE_ADMIN = 'ADMIN'
ALL_ROLES = (ROLE_CITIZEN, ROLE_WORKER, ROLE_ADMIN)

# ================= COMPLAINT CATEGORIES =================
CATEGORIES = (
    'GARBAGE_DUMP',
    'OVERFLOWING_BIN',
    'PLASTIC_WASTE',
    'CONSTRUCTION_WASTE',
    'DRAIN_WASTE',
    'OPEN_DUMPING',
    'DEAD_ANIMAL',
    'OTHER',
)

# Human-readable labels for categories
CATEGORY_LABELS = {
    'GARBAGE_DUMP': 'Garbage Dump',
    'OVERFLOWING_BIN': 'Overflowing Bin',
    'PLASTIC_WASTE': 'Plastic Waste',
    'CONSTRUCTION_WASTE': 'Construction Waste',
    'DRAIN_WASTE': 'Drain Waste',
    'OPEN_DUMPING': 'Open Dumping',
    'DEAD_ANIMAL': 'Dead Animal',
    'OTHER': 'Other',
}

# ================= PRIORITIES =================
PRIORITY_LOW = 'LOW'
PRIORITY_MEDIUM = 'MEDIUM'
PRIORITY_HIGH = 'HIGH'
PRIORITY_CRITICAL = 'CRITICAL'
PRIORITIES = (PRIORITY_LOW, PRIORITY_MEDIUM, PRIORITY_HIGH, PRIORITY_CRITICAL)

# ================= COMPLAINT STATUS =================
COMPLAINT_SUBMITTED         = 'SUBMITTED'
COMPLAINT_UNDER_REVIEW      = 'UNDER_REVIEW'
COMPLAINT_VERIFIED          = 'VERIFIED'
COMPLAINT_REJECTED          = 'REJECTED'
COMPLAINT_ASSIGNED          = 'ASSIGNED'
COMPLAINT_IN_PROGRESS       = 'IN_PROGRESS'
COMPLAINT_WORKER_COMPLETED  = 'WORKER_COMPLETED'
COMPLAINT_ADMIN_VERIFIED    = 'ADMIN_VERIFIED'
COMPLAINT_CLOSED            = 'CLOSED'
COMPLAINT_CANCELLED         = 'CANCELLED'

COMPLAINT_STATUSES = (
    COMPLAINT_SUBMITTED,
    COMPLAINT_UNDER_REVIEW,
    COMPLAINT_VERIFIED,
    COMPLAINT_REJECTED,
    COMPLAINT_ASSIGNED,
    COMPLAINT_IN_PROGRESS,
    COMPLAINT_WORKER_COMPLETED,
    COMPLAINT_ADMIN_VERIFIED,
    COMPLAINT_CLOSED,
    COMPLAINT_CANCELLED,
)

# Valid complaint status transitions
COMPLAINT_TRANSITIONS = {
    COMPLAINT_SUBMITTED:        {COMPLAINT_UNDER_REVIEW, COMPLAINT_CANCELLED},
    COMPLAINT_UNDER_REVIEW:     {COMPLAINT_VERIFIED, COMPLAINT_REJECTED, COMPLAINT_CANCELLED},
    COMPLAINT_VERIFIED:         {COMPLAINT_ASSIGNED, COMPLAINT_REJECTED},
    COMPLAINT_ASSIGNED:         {COMPLAINT_IN_PROGRESS, COMPLAINT_CANCELLED},
    COMPLAINT_IN_PROGRESS:      {COMPLAINT_WORKER_COMPLETED, COMPLAINT_CANCELLED},
    COMPLAINT_WORKER_COMPLETED: {COMPLAINT_ADMIN_VERIFIED, COMPLAINT_REJECTED},
    COMPLAINT_ADMIN_VERIFIED:   {COMPLAINT_CLOSED},
    COMPLAINT_REJECTED:         set(),
    COMPLAINT_CLOSED:           set(),
    COMPLAINT_CANCELLED:        set(),
}

# ================= PICKUP STATUS =================
PICKUP_SUBMITTED    = 'SUBMITTED'
PICKUP_UNDER_REVIEW = 'UNDER_REVIEW'
PICKUP_APPROVED     = 'APPROVED'
PICKUP_ASSIGNED     = 'ASSIGNED'
PICKUP_COMPLETED    = 'COMPLETED'
PICKUP_REJECTED     = 'REJECTED'
PICKUP_CANCELLED    = 'CANCELLED'

PICKUP_STATUSES = (
    PICKUP_SUBMITTED,
    PICKUP_UNDER_REVIEW,
    PICKUP_APPROVED,
    PICKUP_ASSIGNED,
    PICKUP_COMPLETED,
    PICKUP_REJECTED,
    PICKUP_CANCELLED,
)

# ================= TASK STATUS =================
TASK_ASSIGNED            = 'ASSIGNED'
TASK_ACCEPTED            = 'ACCEPTED'
TASK_IN_PROGRESS         = 'IN_PROGRESS'
TASK_COMPLETED           = 'COMPLETED'
TASK_VERIFICATION_FAILED = 'VERIFICATION_FAILED'
TASK_VERIFIED            = 'VERIFIED'
TASK_CANCELLED           = 'CANCELLED'

TASK_STATUSES = (
    TASK_ASSIGNED,
    TASK_ACCEPTED,
    TASK_IN_PROGRESS,
    TASK_COMPLETED,
    TASK_VERIFICATION_FAILED,
    TASK_VERIFIED,
    TASK_CANCELLED,
)

# ================= DUPLICATE STATUS =================
DUP_NOT_CHECKED       = 'NOT_CHECKED'
DUP_UNIQUE            = 'UNIQUE'
DUP_POSSIBLE          = 'POSSIBLE_DUPLICATE'
DUP_DUPLICATE         = 'DUPLICATE'
DUPLICATE_STATUSES    = (DUP_NOT_CHECKED, DUP_UNIQUE, DUP_POSSIBLE, DUP_DUPLICATE)

# ================= TOKEN TRANSACTION =================
TX_EARN       = 'EARN'
TX_SPEND      = 'SPEND'
TX_ADJUSTMENT = 'ADJUSTMENT'
TX_REVERSAL   = 'REVERSAL'
TX_TYPES      = (TX_EARN, TX_SPEND, TX_ADJUSTMENT, TX_REVERSAL)

# Token source types
SRC_COMPLAINT          = 'COMPLAINT'
SRC_PICKUP             = 'PICKUP'
SRC_COMMUNITY_ACTIVITY = 'COMMUNITY_ACTIVITY'
SRC_ADMIN_ADJUSTMENT   = 'ADMIN_ADJUSTMENT'
TOKEN_SOURCE_TYPES     = (SRC_COMPLAINT, SRC_PICKUP, SRC_COMMUNITY_ACTIVITY, SRC_ADMIN_ADJUSTMENT)

# ================= NOTIFICATION TYPES =================
NOTIF_COMPLAINT_SUBMITTED = 'COMPLAINT_SUBMITTED'
NOTIF_COMPLAINT_VERIFIED  = 'COMPLAINT_VERIFIED'
NOTIF_COMPLAINT_REJECTED  = 'COMPLAINT_REJECTED'
NOTIF_WORKER_ASSIGNED     = 'WORKER_ASSIGNED'
NOTIF_TASK_STARTED        = 'TASK_STARTED'
NOTIF_TASK_COMPLETED      = 'TASK_COMPLETED'
NOTIF_WORK_VERIFIED       = 'WORK_VERIFIED'
NOTIF_COMPLAINT_CLOSED    = 'COMPLAINT_CLOSED'
NOTIF_TOKENS_CREDITED     = 'TOKENS_CREDITED'
NOTIF_PICKUP_UPDATED      = 'PICKUP_UPDATED'

# ================= FILE UPLOAD =================
ALLOWED_EXTENSIONS = {'jpg', 'jpeg', 'png', 'webp'}
ALLOWED_MIME_TYPES = {'image/jpeg', 'image/png', 'image/webp'}
MAX_FILE_SIZE_MB   = 5

# ================= PAGINATION =================
DEFAULT_PAGE_SIZE = 20
MAX_PAGE_SIZE     = 100

# ================= ERROR CODES =================
ERR_VALIDATION        = 'VALIDATION_ERROR'
ERR_AUTH_REQUIRED     = 'AUTH_REQUIRED'
ERR_INVALID_CREDS     = 'INVALID_CREDENTIALS'
ERR_ACCOUNT_INACTIVE  = 'ACCOUNT_INACTIVE'
ERR_FORBIDDEN         = 'FORBIDDEN'
ERR_NOT_FOUND         = 'NOT_FOUND'
ERR_DUPLICATE         = 'DUPLICATE_RESOURCE'
ERR_INVALID_TRANSITION = 'INVALID_STATUS_TRANSITION'
ERR_FILE_INVALID      = 'FILE_INVALID'
ERR_FILE_TOO_LARGE    = 'FILE_TOO_LARGE'
ERR_AI_ERROR          = 'AI_ERROR'
ERR_DATABASE          = 'DATABASE_ERROR'
ERR_INTERNAL          = 'INTERNAL_ERROR'

# ================= AUDIT ACTIONS =================
AUDIT_ADMIN_VERIFIED_COMPLAINT = 'ADMIN_VERIFIED_COMPLAINT'
AUDIT_ADMIN_REJECTED_COMPLAINT = 'ADMIN_REJECTED_COMPLAINT'
AUDIT_WORKER_ASSIGNED          = 'WORKER_ASSIGNED'
AUDIT_ADMIN_VERIFIED_TASK      = 'ADMIN_VERIFIED_TASK'
AUDIT_ADMIN_REJECTED_TASK      = 'ADMIN_REJECTED_TASK'
AUDIT_TOKEN_ADJUSTED           = 'TOKEN_ADJUSTED'
AUDIT_USER_STATUS_CHANGED      = 'USER_STATUS_CHANGED'
AUDIT_ADMIN_LOGIN              = 'ADMIN_LOGIN'